### ISSUE TITLE
lower_bound(0,0)

### ISSUE THREAD

**Issue by kenn** [instacart/wilson_score#3]
Right now, it returns an obscure error:

```ruby
WilsonScore.lower_bound(0,0)
# => ArgumentError: comparison of Float with 0 failed
# from <gem>/wilson_score-0.1.0/lib/wilson_score.rb:20:in `each'
```

That means all apps that can possibly take 0 as the second parameter must special case it. It's not even `ZeroDivisionError`.

Two possible solutions:

- Return 0 as a result (not exactly correct but convenient in most cases)
- Raise a class specific error like `WilsonScore::Error` when 0 is given for the second parameter.

If you give me a direction, I can prepare a pull request.

**Comment by ankane** [comment]
Hey, thanks @kenn. Let's go with 0 as a result.

**Comment by kenn** [comment]
I found a weird edge case...

```ruby
WilsonScore.lower_bound(1,0)
# => ArgumentError: comparison of Float with 0 failed
```

So it returns the same error, but this definitely feels like `ZeroDivisionError` intuitively, and I'm not sure if we should return `0` for this case too... are you still comfortable with 0 as result?

**Comment by ankane** [comment]
Think it should throw an error in that case. I think 0/0 is a bit special, but probably makes sense to throw an error there as well.
